### ISSUE TITLE
Kubernetes cronjob appears to be ignoring the disallowed instance types.

### ISSUE THREAD

**Issue by Reinkaos** [cloudutil/AutoSpotting#456]
Hey,

I am using the Kubernetes cronjob that is provided and I have specified r5d.large in the `DISALLOWED_INSTANCE_TYPES`. I can see that it is coming through in the config, (as below) but it is still starting up these instances. 

```2021/04/08 03:50:16 Starting autospotting agent, build  nightly-931b827 expiring on 25-Apr-2021
2021/04/08 03:50:16 Configuration flags: autospotting.Config{AutoScalingConfig:autospotting.AutoScalingConfig{MinOnDemandNumber:0, MinOnDemandPercentage:0, AllowedInstanceTypes:"*", DisallowedInstanceTypes:"r5d.large", OnDemandPriceMultiplier:1, SpotPriceBufferPercentage:10, SpotProductDescription:"Linux/UNIX (Amazon VPC)", SpotProductPremium:0, BiddingPolicy:"normal", TerminationMethod:"", InstanceTerminationMethod:"autoscaling", TerminationNotificationAction:"auto", CronSchedule:"* *", CronTimezone:"UTC", CronScheduleState:"on", PatchBeanstalkUserdata:""}, InstanceData:(*ec2instancesinfo.InstanceData)(0xc00039f740), LogFile:(*os.File)(0xc000094008), LogFlag:19, Regions:"ap-southeast-2", MainRegion:"us-east-1", SleepMultiplier:1, FilterByTags:"", TagFilteringMode:"opt-in", Version:"nightly-931b827", LicenseType:"evaluation", PatchBeanstalkUserdata:"false", LambdaManageASG:"", EventFile:"", FinalRecap:map[string][]string{}}`
```

```
 Successfully launched spot instance <id> of type r5d.large with bid price xxx.
```

This seems to be have been referenced before https://github.com/AutoSpotting/AutoSpotting/issues/312. 

Please let me know if I am doing something wrong.

**Comment by cristim** [comment]
Thanks for reporting this issue. 

I'm quite busy with other things and I have no plans to look into this for the foreseeable future but if you can figure it out I'd love to see a pull request addressing it.

**Comment by Reinkaos** [comment]
Hey, thanks for letting me know.

**Comment by cristim** [comment]
TBH, I no longer recommend running AutoSpotting as a Kubernetes cronjob, the current event-based implementation improved the instance replacement logic a lot but it requires EventBridge and therefore needs to run from Lambda.

It should still run as a cron job but will only do the classic instance replacement which isn't ideal, so I have no plans to look into this issue but I'd happily consider a PR fixing this.

**Comment by cristim** [comment]
I actually remember something similar, I think the `AllowedInstanceTypes:"*"` takes precedence over ` DisallowedInstanceTypes:"r5d.large"`, so just set it to an empty string, this should do the trick: `AllowedInstanceTypes:""`
