### ISSUE TITLE
LaunchTemplate/LaunchConfiguration VolumeSize overwritten by Image one

### ISSUE THREAD

**Issue by mello7tre** [cloudutil/AutoSpotting#479]
# Github issue #

## Issue type ##

- Bug Report

## Build number #

```
master-fe9850f
```

## Summary ##

Spot instance is launched with a wrong VolumeSize, the default one of the ami.

## Steps to reproduce ##

Use AutoSpotting to replace an instance where the image volume size is different from the one specified in the LaunchTemplate BlockDeviceMappings.

## Expected results ##

Launched Spot should have a disk VolumeSize equals to the LT one.

## Actual results ##
Launched Spot have a disk VolumeSize equals to the image one.

## Possible fix ##
In `core/instance_conversion.go` `createLaunchTemplateData` move `i.processImageBlockDevices(&ltData)` just after `ltData.SecurityGroupIds = i.convertSecurityGroups()`.
This way first is processed ami configuration and then LaunchTemplate/LaunchConfiguration.

I tested it and it seems to work as expected, i will open a PR.

**Comment by cristim** [comment]
Thanks, good catch!
